### ISSUE TITLE
Undefined symbols: _qsnapvectorsse  _qvmftolsse _qftolsse

### ISSUE THREAD

**Issue by Seoras** [tomkidd/RTCW-iOS#1]
Thanks for all the hard work in porting these classics Tom.
I'm running Xcode 10.2.1 and compiling both SP & MP fails at link with Undefined symbols: _qsnapvectorsse  _qvmftolsse _qftolsse
I'm guessing that this is the small bits of assembly in ftola.asm and snapvector.asm neither of which have any target memberships and I can't find references in the build rules.
I'm left wondering if there is another step that you might have omitted from the README?

**Comment by tomkidd** [comment]
I have no idea why GitHub wasn't automatically telling me about these issues being posted. I'm now "watching" the repo so hopefully they start.

Anyway this issue is over a year old but I think it no longer happens. I used to have "Simulator" and regular targets because... it's a long story but check the Quake 3 article for more info. Anyway I figured a way around the issue so now it should just work everywhere.
