### ISSUE TITLE
Still crashs when choosing difficulty on iOS 13

### ISSUE THREAD

**Issue by ewewo2** [tomkidd/RTCW-iOS#12]
Still crashs when choosing difficulty on iOS

**Comment by dnicolson** [comment]
Fixed in https://github.com/tomkidd/RTCW-iOS/pull/11.

**Comment by ewewo2** [comment]
still crashes on ios 13

**Comment by dnicolson** [comment]
The fix isn't merged yet, you need to apply the changes yourself until it is.

**Comment by tomkidd** [comment]
We've determined that the crash @dnicolson was experiencing was related to something else, so the code as it sits right now should work. 

When you choose difficulty, the game engine actually starts, so if there's issues with the data files that's where it will happen. 

In addition to the need to specify the `Main` folder containing your RTCW data files, you also need to copy the ["vm"](https://github.com/tomkidd/RTCW-iOS/tree/master/Main/vm) folder from the repo to that same `Main` folder with your data files. This was not well explained before but I've since gone in and added some clarification to the [README](https://github.com/tomkidd/RTCW-iOS/blob/master/README.md).

So check that and if you still get issues post a log here.
